services:
  webserver:
    container_name: webserver_instance
    restart: on-failure
    depends_on:
      - backend
    build:
      dockerfile: ./Dockerfile.nginx
    ports:
      - 80:80
    networks:
      - infrastructure
  backend:
    container_name: backend_instance
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./_infra/Dockerfile
    env_file:
      - ../.env
    environment:
      APPLICATION_PORT: 5000
      DATABASE_HOST: mysql
    networks:
      - infrastructure
  mysql:
    container_name: mysql_instance
    restart: on-failure
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "todo_list"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/scripts/init.sql
      - ./init-mysql.sh:/scripts/init-mysql.sh
    healthcheck:
      test: ["CMD", "/bin/bash", "/scripts/init-mysql.sh"]
    networks:
      - infrastructure
volumes:
  mysql-data:
networks:
  infrastructure:
